### ISSUE TITLE
Cross-model references in UML models

### ISSUE THREAD

**Issue by kolovos** [mondo-project/mondo-hawk#57] opened 2018-03-13 23:37 UTC
Hawk doesn't seem to be correctly indexing cross-model references in Eclipse UML models. To reproduce, import the projects in the [attached archive](https://github.com/mondo-project/mondo-hawk/files/1809055/cross-model-references.zip), create a Hawk instance that indexes either the entire workspace or the model1 and model2 folders and run `epsilon/allclasses.eol` against it. The models contain two generalizations; one is between Class 1 (in model1) and Class 2 (in model2) and one is between Class2 and Class3 (both in model2). The `.general` property of the first one returns null (when it should return Class1).

On an unrelated topic, trying to run a `.all.select` with an error in the selection condition (e.g. `Generalization.all.select(g|g.general1.isUndefined()).println();
`) produces a somewhat cryptic error: `OptimisableCollectionSelectOperation: parseAST[iterator, ast] failed`

**Comment by kolovos** [comment] 2018-03-14 09:34
Interestingly, if I index the parent folder of model1 and model2 as a local folder, it works as expected.

**Comment by bluezio** [comment] 2018-03-14 09:38
Thanks for the update! Fragments in separate locations (i.e. having model1 and model2 as their own LocalFolders) are never linked together with the current design, and that is intentional - conceptually they belong to different collections.

What is puzzling is what might be happening when indexing within a workspace. I'll have a look at it ASAP.

**Comment by bluezio** [comment] 2018-03-14 09:49
I have confirmed the issue when indexing within a workspace. I have used this query:

```
return Class.all.collect(c | Sequence {
  c.name, c.generalization, c.generalization.general }).asSequence;
```

Given `platform:/resource` as the context repository, that produces (focusing on the null):
```
[[Class1, [], []], [Class3, [], []], [Class2, [GNW|id:633|type:Generalization, GNW|id:632|type:Generalization], [GNW|id:634|type:Class, null]]]
```

Sounds like something may be wrong in the way relative paths are resolved when working from a workspace. I'll have a look at it.

(Also noted the issue with that unhelpful error reporting: we already capture and translate some errors from EOL into more helpful messages, but we have missed this case.)

**Comment by bluezio** [comment] 2018-03-14 09:50
Also confirmed that it works fine from a LocalFolder. There's definitely something wrong in how relative paths are resolved within a workspace.

**Closed** 2018-03-14 15:05 UTC

**Comment by bluezio** [comment] 2018-03-14 15:09
This is now fixed. The problem is that Hawk entirely relied on the URIs provided by IHawkObject, and didn't have the smarts to turn a filesystem location (file:/path/to/project/file) back into a workspace location (/project/file).

At most, it could only remove some prefixes reported by the IVcsManager. However, Eclipse projects do not have to be within the workspace root folder, so we need something more general.

I have dropped `getPrefixesToBeStripped(String)` from IVcsManager and replaced it with a more general `getRepositoryPath(String)`. The Workspace IVcsManager can then rely on `ResourcesPlugin` to provide the workspace-relative path of that file.
