### ISSUE TITLE
Issue when creating a Thrift Remote Hawk Factory instance in the user interface

### ISSUE THREAD

**Issue by beatrizsanchez** [mondo-project/mondo-hawk#67] opened 2018-08-16 12:42 UTC
I have installed the latest version of (all plugins of) Hawk and Epsilon but I get an "At least one updater plugin must be enabled" error when trying to create a Thrift client. When switching from LocalHawkFactory and ThriftFactory the GraphModelUpdater disappears from the available plugins to be enabled.

<img width="647" alt="screen shot 2018-08-16 at 9 40 17 am" src="https://user-images.githubusercontent.com/6515216/44208945-3140d700-a162-11e8-8a47-efa911bd171d.png">

OS: OSX

**Comment by bluezio** [comment] 2018-09-08 20:08
Sorry for the delay: had quite a bit to catch up on after the holidays. I have just tried doing this while running the server straight from source, and the GraphModelUpdater did appear within the dialog when I had the ThriftRemoteHawkFactory selected.

Could you provide more info on how you installed the server? Did you download one of the zip files in the release section, or did you install it from an update site?

If you downloaded one of the server zips from the release section, you may have run into this issue, as older versions of Hawk did not allow you to enable/disable updater plugins (there was only one back then, after all!). Running the server from the source should help.

I will upload new products ASAP, so we may avoid this issue from other users. Thanks for the update!

**Comment by bluezio** [comment] 2018-09-08 22:37
Created new release here:

https://github.com/mondo-project/mondo-hawk/releases/tag/20180908-interim

Please try the server here, and let me know how it goes!

**Comment by beatrizsanchez** [comment] 2018-09-09 07:53
Hi Antonio, don't worry for the delay. Thanks for the new product. 
I believe I used an update site when I installed all plugins. I tried to install all plugins again with the new update site and I got the following message during installation from archive: 
<img width="813" alt="screen shot 2018-09-09 at 8 16 20 am" src="https://user-images.githubusercontent.com/6515216/45262182-d3727880-b409-11e8-91ea-78c0899d0901.png">
I don't believe this is a bug but it would help to know where to get the dependencies from.

When I try to run from source (in a clean basic eclipse installation) I have several issues.
1 - Although the target platform is loaded and has no issues, when I try to validate the plugins of the run configuration (on mac) using all target dependencies I get several conflicts regarding other operating systems
<img width="1073" alt="screen shot 2018-09-09 at 8 44 29 am" src="https://user-images.githubusercontent.com/6515216/45262346-ef2b4e00-b40c-11e8-802a-978891b43664.png">
2 - If I remove all plugins of other OS (as seen on the image below), and run the application (without hawk) the running eclipse instance does not allow me to click on anything: no menus can be open, the application can't be closed, nothing I can only force quit it.
<img width="797" alt="screen shot 2018-09-09 at 8 45 00 am" src="https://user-images.githubusercontent.com/6515216/45262371-48937d00-b40d-11e8-971e-e382fc36f53a.png">

Just in case, I am running the source with the latest pull but not from the archived source code in the releases. I bring this target platform issue up because otherwise I rely on releases to run Hawk instead of the source code.

**Comment by beatrizsanchez** [comment] 2018-09-09 08:08
Sorry for the incomplete post above, I just tried again the installation from the update site without the conflicting plugins (see below) 
<img width="1440" alt="screen shot 2018-09-09 at 8 56 57 am" src="https://user-images.githubusercontent.com/6515216/45262437-7af1aa00-b40e-11e8-8e36-af83e301e195.png">

and was able to create a Thrift client the first time: The server was running and the UI showed the necessary plugins for the Thrift client to be created.
```
<hawkProperties>
  <dbType>dummy</dbType>
  <monitoredVCS class="list"/>
  <minDelay>5000</minDelay>
  <maxDelay>512000</maxDelay>
</hawkProperties>
```
However, I tried to create a second thrift client and the plugins mysteriously disappeared again:

<img width="691" alt="screen shot 2018-09-09 at 9 02 27 am" src="https://user-images.githubusercontent.com/6515216/45262500-cbb5d280-b40f-11e8-8e18-d333a2d7caae.png">
<img width="698" alt="screen shot 2018-09-09 at 9 02 34 am" src="https://user-images.githubusercontent.com/6515216/45262503-ce182c80-b40f-11e8-83c9-473d5edb3da2.png">
<img width="698" alt="screen shot 2018-09-09 at 9 02 41 am" src="https://user-images.githubusercontent.com/6515216/45262505-d07a8680-b40f-11e8-88a8-e7e02c284d14.png">

**Comment by bluezio** [comment] 2018-09-09 12:30
Unfortunately, I cannot add a reference to the SVNKit update site from the zipped update site itself (it's a [limitation](https://bugs.eclipse.org/bugs/show_bug.cgi?id=453708) in Tycho). I have touched up the description of the release so it mentions the additional update sites you will need to register before using that zipped update site.

(The regular Hawk update site is a composite site which does point to a repository with the SVNKit plugins, so it doesn't require doing anything of this.)

I will try to reproduce your issue in a few hours.

**Comment by bluezio** [comment] 2018-09-09 15:28
This is quite strange: I can't reproduce your issue. I have tried this:

* Run the nogpl server from source, run Hawk UI from source, create a Thrift-based client, then try to create a second one, and switch back and forth between local/time-aware/remote to try and see the plugin disappearing.
* Run the nogpl server from the built product, run Hawk UI from source, create a Thrift-based client, then try the same thing as before.

Can you email me to set up a Skype talk to see what might be happening? It's quite odd.

**Comment by bluezio** [comment] 2018-09-18 10:27
Can you confirm if this works now with the latest version of Hawk, running on top of Eclipse Photon?

**Comment by beatrizsanchez** [comment] 2018-09-18 16:01
Hi Antonio, it's fixed for oxygen running from source. Thanks :)

**Comment by bluezio** [comment] 2018-09-18 16:28
No problem :-). Closing the issue, then.

**Closed by bluezio** 2018-09-18 16:28 UTC
